#!/usr/bin/awk -f
# trim: Trim lines to terminal width and show at most 10 lines
#
# Author: Jeroen Janssens (https://jeroenjanssens.com)

BEGIN {
    "tput cols" | getline width
    height = 10
}

NR <= height {
    if (length($0) > width) {
        print substr($0, 1, width - 1) "…"
    } else {
        print
    }
}

END {
    if (NR == height + 1) {
        print
    } else if (NR > height + 1) {
        print "… with " (NR - height) " more lines" > "/dev/stderr"
    }
}
